"""
Domain Models — Dataclasses representing core domain entities in potbot.
"""

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional


@dataclass
class Document:
    """Represents an ingested document file or section."""

    text: str
    source_file: str
    file_name: str
    file_type: str
    page_number: Optional[int] = None
    total_pages: Optional[int] = None
    modified_date: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class Chunk:
    """Represents a chunk of text extracted from a Document with vector embeddings."""

    chunk_id: str
    doc_id: str
    text: str
    chunk_index: int
    source_file: str
    file_name: str
    file_type: str
    page_number: Optional[int] = None
    modified_date: Optional[str] = None
    embedding: Optional[List[float]] = None
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class SearchResult:
    """Represents a retrieved document chunk from the search index."""

    chunk_id: str
    doc_id: str
    text: str
    file_name: str
    source_file: str
    file_type: str
    page_number: Optional[int] = None
    score: float = 0.0
    rrf_score: Optional[float] = None
    rerank_score: Optional[float] = None
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class RAGResponse:
    """Represents the complete response generated by the RAG pipeline."""

    answer: str
    query: str
    rewritten_query: Optional[str]
    retrieved_docs: List[SearchResult]
    model: str
    prompt_style: str
    retrieval_method: str
    response_time_ms: int
    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0
    conversation_id: Optional[int] = None


@dataclass
class FeedbackRecord:
    """Represents user feedback for a conversation."""

    conversation_id: int
    sentiment: str  # 'positive' or 'negative'
    comment: Optional[str] = None
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
