apiVersion: 1

datasources:
  - name: PostgreSQL-SecureRAG
    type: postgres
    access: proxy
    url: postgres:5432
    user: securerag
    database: securerag
    secureJsonData:
      password: securerag_secret
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 3
      connMaxLifetime: 14400
      postgresVersion: 1600
    isDefault: true
